# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 1

before:
  hooks:
    - go mod tidy

builds:
  - binary: grpc
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

brews:
  -
    name: grpcmd
    description: "A simple, easy-to-use, and developer-friendly CLI tool for gRPC."
    homepage: "https://github.com/grpcmd/grpcmd"
    repository:
      owner: grpcmd
      name: homebrew-tap
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    extra_install: |
      (bash_completion/"grpc").write `#{bin}/grpc completion bash`
      (fish_completion/"grpc.fish").write `#{bin}/grpc completion fish`
      (zsh_completion/"_grpc").write `#{bin}/grpc completion zsh`

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
